USE master

CREATE DATABASE [CdrDb_$(DB_NAME_SUFFIX)]
ON (NAME = N'CdrDb_$(DB_NAME_SUFFIX)_Data',
FILENAME = N'$(DB_DIR)\CdrDb_$(DB_NAME_SUFFIX)_Data.MDF',
SIZE = 64MB,
FILEGROWTH = 64MB)
LOG ON (NAME = N'CdrDb_$(DB_NAME_SUFFIX)_Log',
FILENAME = N'$(DB_DIR)\CdrDb_$(DB_NAME_SUFFIX)_Log.LDF',
SIZE = 7,
FILEGROWTH = 10%)

ALTER DATABASE [CdrDb_$(DB_NAME_SUFFIX)] SET AUTO_CLOSE OFF WITH NO_WAIT