using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.71.0")]
[assembly: AssemblyCopyrightAttribute("Copyright  2003-2009 Timok.es LLC.")]
[assembly: AssemblyCompanyAttribute("Timok.es LLC.")]
[assembly: AssemblyProductAttribute("Timok.Rbr.Softswitch")]

