USE [RbrDb_$(DB_VERSION)]
GO
CREATE USER [$(COMP_NAME)\ASPNET] FOR LOGIN [$(COMP_NAME)\ASPNET] --WITH DEFAULT_SCHEMA=[dbo]
GO
USE [RbrDb_$(DB_VERSION)]
GO
EXEC sp_addrolemember N'db_owner', N'$(COMP_NAME)\ASPNET'
GO
