/*** [<<CDRDB_NAME>>] ***/
CREATE USER [NT AUTHORITY\NETWORK SERVICE] FOR LOGIN [NT AUTHORITY\NETWORK SERVICE]; --WITH DEFAULT_SCHEMA=[dbo]
EXEC sp_addrolemember N'db_owner', N'NT AUTHORITY\NETWORK SERVICE'

