--DELETE ORDER:
-----------------------------------------
TRUNCATE TABLE RbrDb_$(DB_VERSION).dbo.CdrAggregate
-----------------------------------------
TRUNCATE TABLE RbrDb_$(DB_VERSION).dbo.InventoryHistory
TRUNCATE TABLE RbrDb_$(DB_VERSION).dbo.InventoryUsage
-----------------------------------------
DELETE FROM RbrDb_$(DB_VERSION).dbo.CdrExportMapDetail
DELETE FROM RbrDb_$(DB_VERSION).dbo.CdrExportMap
DELETE FROM RbrDb_$(DB_VERSION).dbo.Rate
DELETE FROM RbrDb_$(DB_VERSION).dbo.TimeOfDayPeriod
DELETE FROM RbrDb_$(DB_VERSION).dbo.TypeOfDay
DELETE FROM RbrDb_$(DB_VERSION).dbo.HolidayCalendar
DELETE FROM RbrDb_$(DB_VERSION).dbo.TimeOfDay
DELETE FROM RbrDb_$(DB_VERSION).dbo.TimeOfDayPolicy
DELETE FROM RbrDb_$(DB_VERSION).dbo.TypeOfDayChoice
DELETE FROM RbrDb_$(DB_VERSION).dbo.CarrierRateHistory
DELETE FROM RbrDb_$(DB_VERSION).dbo.WholesaleRateHistory
DELETE FROM RbrDb_$(DB_VERSION).dbo.ResellRateHistory
DELETE FROM RbrDb_$(DB_VERSION).dbo.RetailRateHistory
DELETE FROM RbrDb_$(DB_VERSION).dbo.RateInfo
DELETE FROM RbrDb_$(DB_VERSION).dbo.WholesaleRoute
DELETE FROM RbrDb_$(DB_VERSION).dbo.RetailRoute
DELETE FROM RbrDb_$(DB_VERSION).dbo.Batch
DELETE FROM RbrDb_$(DB_VERSION).dbo.Box
DELETE FROM RbrDb_$(DB_VERSION).dbo.GenerationRequest
DELETE FROM RbrDb_$(DB_VERSION).dbo.InventoryLot
DELETE FROM RbrDb_$(DB_VERSION).dbo.TerminationChoice
DELETE FROM RbrDb_$(DB_VERSION).dbo.CustomerAcctPayment
DELETE FROM RbrDb_$(DB_VERSION).dbo.CustomerAcctSupportMap
DELETE FROM RbrDb_$(DB_VERSION).dbo.CallCenterCabina
DELETE FROM RbrDb_$(DB_VERSION).dbo.PhoneCard
DELETE FROM RbrDb_$(DB_VERSION).dbo.ResidentialPSTN
DELETE FROM RbrDb_$(DB_VERSION).dbo.ResidentialVoIP
DELETE FROM RbrDb_$(DB_VERSION).dbo.RetailAccountPayment
DELETE FROM RbrDb_$(DB_VERSION).dbo.RetailRouteBonusMinutes
DELETE FROM RbrDb_$(DB_VERSION).dbo.RetailAccount
DELETE FROM RbrDb_$(DB_VERSION).dbo.BalanceAdjustmentReason
DELETE FROM RbrDb_$(DB_VERSION).dbo.LCRBlackList
DELETE FROM RbrDb_$(DB_VERSION).dbo.OutboundANI
DELETE FROM RbrDb_$(DB_VERSION).dbo.CarrierAcctEPMap
DELETE FROM RbrDb_$(DB_VERSION).dbo.CarrierRoute
DELETE FROM RbrDb_$(DB_VERSION).dbo.CarrierAcct
DELETE FROM RbrDb_$(DB_VERSION).dbo.CustomerSupportGroup
DELETE FROM RbrDb_$(DB_VERSION).dbo.CustomerSupportVendor
DELETE FROM RbrDb_$(DB_VERSION).dbo.ResellAcct
DELETE FROM RbrDb_$(DB_VERSION).dbo.LoadBalancingMap
DELETE FROM RbrDb_$(DB_VERSION).dbo.DialPeer
DELETE FROM RbrDb_$(DB_VERSION).dbo.AccessNumberList
DELETE FROM RbrDb_$(DB_VERSION).dbo.CustomerAcct
DELETE FROM RbrDb_$(DB_VERSION).dbo.Person
DELETE FROM RbrDb_$(DB_VERSION).dbo.PayphoneSurcharge
DELETE FROM RbrDb_$(DB_VERSION).dbo.Service
DELETE FROM RbrDb_$(DB_VERSION).dbo.IPAddress
DELETE FROM RbrDb_$(DB_VERSION).dbo.EndPoint
DELETE FROM RbrDb_$(DB_VERSION).dbo.Partner
DELETE FROM RbrDb_$(DB_VERSION).dbo.Schedule
DELETE FROM RbrDb_$(DB_VERSION).dbo.RoutingPlanDetail
DELETE FROM RbrDb_$(DB_VERSION).dbo.RoutingPlan
DELETE FROM RbrDb_$(DB_VERSION).dbo.DialCode
DELETE FROM RbrDb_$(DB_VERSION).dbo.Route
DELETE FROM RbrDb_$(DB_VERSION).dbo.Country
DELETE FROM RbrDb_$(DB_VERSION).dbo.CallingPlan
DELETE FROM RbrDb_$(DB_VERSION).dbo.VirtualSwitch
DELETE FROM RbrDb_$(DB_VERSION).dbo.ContactInfo
DELETE FROM RbrDb_$(DB_VERSION).dbo.Node
DELETE FROM RbrDb_$(DB_VERSION).dbo.Platform
DELETE FROM RbrDb_$(DB_VERSION).dbo.PrefixInType
DELETE FROM RbrDb_$(DB_VERSION).dbo.TableSequence

