BULK INSERT RbrDb_$(DB_VERSION).dbo.Country FROM '$(IMPORT_FILES_PATH)\Country.txt' WITH (BATCHSIZE = 1000)
BULK INSERT RbrDb_$(DB_VERSION).dbo.Route FROM '$(IMPORT_FILES_PATH)\Route.txt' WITH (BATCHSIZE = 1000)
BULK INSERT RbrDb_$(DB_VERSION).dbo.DialCode FROM '$(IMPORT_FILES_PATH)\DialCode.txt' WITH (BATCHSIZE = 1000)
